benchmark_name: verite
benchmark_kwargs:
  variant: dev
fact_checker_kwargs:
  decompose: false
  decontextualize: false
  filter_check_worthy: false
  interpret: false
  max_iterations: 3
  max_result_len: 64000
  procedure_variant: summary/dynamic
llm: gpt_4o
llm_kwargs:
  temperature: 0.01
n_samples:
random_sampling: false
sample_ids: null
allowed_actions:
- web_search
- image_search
- reverse_search
- geolocate
tools_config:
  searcher:
    limit_per_search: 3
    search_config:
      google:
  geolocator:
n_workers: 8
print_log_level: info
